name: sdf_net
channels:
  - https://repo.anaconda.com/pkgs/free
  - pytorch
  - intel
  - ostrokach
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - blas=2.11=openblas
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2019.11.28=py36_0
  - cffi=1.12.3=py36h8022711_0
  - cloudpickle=1.2.1=py_0
  - cycler=0.10.0=py_1
  - cython=0.29.2=py36hf484d3e_1000
  - cytoolz=0.10.0=py36h516909a_0
  - dask-core=2.3.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - embree=2.14.0=0
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.9=h516909a_0
  - glew=1.13.0=3
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - icu=58.2=hf484d3e_1000
  - imageio=2.4.1=py36_1000
  - importlib_metadata=0.20=py36_0
  - intel-openmp=2019.4=243
  - intelpython=2020.0=1
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h5a2b251_1
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.1=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.0.3=py36_1
  - matplotlib-base=3.0.3=py36h5f35d83_1
  - mkl=2019.5=intel_281
  - mkl-include=2019.5=281
  - more-itertools=7.2.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=h6bb024c_0
  - numpy=1.15.4=py36h99e49ec_0
  - numpy-base=1.15.4=py36h2f8d375_0
  - olefile=0.46=py_0
  - openblas=0.3.3=h9ac9557_1001
  - opencv=4.1.1=py36ha799480_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h516909a_0
  - pandas=0.23.4=py36h637b7d7_1000
  - pcre=8.41=hf484d3e_1003
  - pillow=5.3.0=py36h00a061d_1000
  - pip=19.2.3=py36_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.12.0=py_0
  - protobuf=3.9.1=py36he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.8.0=py_0
  - pycparser=2.19=py36_1
  - pyembree=0.1.4=py36h637b7d7_1001
  - pymesh2=0.2.1=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt
  - pytest=4.0.2=py36_1000
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=3.13=py36h14c3975_1001
  - qt=5.9.7=h52cfd70_2
  - readline=8.0=hf8c457e_0
  - scikit-image=0.14.1=py36hf484d3e_1004
  - scipy=1.1.0=py36he2b7bc3_2
  - setuptools=41.2.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.29.0=hcee41ef_1
  - system=5.8=2
  - tbb=2019.8=intel_281
  - tensorboardx=1.4=py_0
  - tk=8.6.9=hed695b0_1002
  - toolz=0.10.0=py_0
  - torchvision=0.2.2
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.28.1=py_0
  - trimesh=2.37.7=py_0
  - wheel=0.33.6=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - freetype-py==2.1.0.post1
    - future==0.17.1
    - h5py==2.9.0
    - networkx==2.2
    - plyfile==0.7
    - pyglet==1.4.0b1
    - pymesh==1.0.2
    - pyopengl==3.1.0
    - pyrender==0.1.30
prefix: /home/athai6/anaconda3/envs/sdf_net

